apiVersion: v1
kind: ConfigMap
metadata:
  name: test-con-nginx-tpl-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  consul-template-config.hcl: |-
    {{ tpl (.Files.Get "config-files/consul-template-config.hcl" | nindent 4 ) . }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-vault-agent-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  vault-agent-config.hcl: |-
    {{ tpl (.Files.Get "config-files/vault-agent-config.hcl" | nindent 4 ) . }}
